language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-banjocanyon/latest
  - mkdir -p deploy/meshblu-banjocanyon/$TRAVIS_TAG
  - node_modules/.bin/browserify -t coffeeify -s Connector connector.js > deploy/meshblu-banjocanyon/latest/meshblu-banjocanyon.js
  - gzip deploy/meshblu-banjocanyon/latest/meshblu-banjocanyon.js
  - mv deploy/meshblu-banjocanyon/latest/meshblu-banjocanyon.js.gz deploy/meshblu-banjocanyon/latest/meshblu-banjocanyon.js
  - cp deploy/meshblu-banjocanyon/latest/meshblu-banjocanyon.js deploy/meshblu-banjocanyon/$TRAVIS_TAG/meshblu-banjocanyon.js
deploy:
  - provider: s3
    region: us-west-2
    skip_cleanup: true
    detect_encoding: true
    access_key_id: AKIAJH2D5IPIRHYJT5IA
    secret_access_key:
      secure: "Aw6NTBKNhSn35jHUfslBnt4aPKUajn/lrNRfXu/MikUM/oDNqU04XochhkqI0xiKReQmYdBse56v2x+RdvSy/qPVjJuHqQxLQFE8eEDTTfFpV/ycVGGTYt7rAtogqDQUT9Jkmj0Uk32mVYSThS1Wwz5C5NkuJFo4A/vIBegXVS0="
    bucket: octoblu-cdn
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "pZgnk6E9vMZP7voaCxRa2YWbl+5fkeE7oD4XfkwKfNaRIbl1PvDFmAcmnucdVkuMSD7vCEY8LzDSvljiUSTWS8wa2LKcdPAy4j4WimMQqqvtHgx0m+Fd3ZMNhyUHE9/LDkcb16gUSKrAfS8BE0PCqHYb5zSfpeSOZg+TmM8c9aA="
    on:
      tags: true
      all_branches: true
